import type { BookStack } from "@/types/books";

export const BOOK_STACKS: BookStack[] = [
  {
    id: "stack-seed-1",
    label: "Stack seed 1",
    books: [
      {
        id: "why-fish-dont-exist",
        title: "Why Fish Don't Exist",
        author: "Lulu Miller",
        readMoreUrl: "https://en.wikipedia.org/wiki/Why_Fish_Don%27t_Exist",
        wordCount: 70000,
        offset: -2,
        coverGradient: "linear-gradient(135deg, #d8eadf 0%, #b7d4df 100%)",
      },
      {
        id: "dune",
        title: "Dune",
        author: "Frank Herbert",
        readMoreUrl: "https://en.wikipedia.org/wiki/Dune_(novel)",
        wordCount: 161751,
        offset: 1,
        coverGradient: "linear-gradient(135deg, #ead8bd 0%, #d7b6a5 100%)",
      },
      {
        id: "zero-to-one",
        title: "Zero to One",
        author: "Peter Thiel with Blake Masters",
        readMoreUrl: "https://en.wikipedia.org/wiki/Zero_to_One",
        wordCount: 53000,
        offset: -1,
        coverGradient: "linear-gradient(135deg, #d8dbe8 0%, #b9c5d8 100%)",
      },
      {
        id: "the-prince",
        title: "The Prince",
        author: "Niccolo Machiavelli",
        readMoreUrl: "https://en.wikipedia.org/wiki/The_Prince",
        wordCount: 42000,
        offset: 3,
        coverGradient: "linear-gradient(135deg, #e0c8c2 0%, #c8b1bc 100%)",
      },
      {
        id: "frankenstein",
        title: "Frankenstein",
        author: "Mary Shelley",
        readMoreUrl: "https://en.wikipedia.org/wiki/Frankenstein",
        wordCount: 75380,
        offset: -3,
        coverGradient: "linear-gradient(135deg, #cbdac8 0%, #b2c1b8 100%)",
      },
      {
        id: "mckinsey-way",
        title: "The McKinsey Way",
        author: "Ethan M. Rasiel",
        readMoreUrl:
          "https://www.mheducation.com/highered/mhp/product/mckinsey-way.html",
        wordCount: 54000,
        offset: 2,
        coverGradient: "linear-gradient(135deg, #d8d2c1 0%, #b7c6d0 100%)",
      },
      {
        id: "tao-te-ching",
        title: "Tao Te Ching",
        author: "Lao Tzu",
        readMoreUrl: "https://en.wikipedia.org/wiki/Tao_Te_Ching",
        wordCount: 17000,
        offset: 0,
        coverGradient: "linear-gradient(135deg, #cfdfd4 0%, #b7cbd1 100%)",
      },
      {
        id: "creative-act",
        title: "The Creative Act",
        author: "Rick Rubin",
        readMoreUrl: "https://sites.prh.com/thecreativeact",
        wordCount: 60000,
        offset: -1,
        coverGradient: "linear-gradient(135deg, #e2d8c8 0%, #c7bfdb 100%)",
      },
    ],
  },
  {
    id: "stack-seed-2",
    label: "Stack seed 2",
    books: [
      {
        id: "meditations",
        title: "Meditations",
        author: "Marcus Aurelius",
        readMoreUrl:
          "https://en.wikipedia.org/wiki/Meditations_of_Marcus_Aurelius",
        wordCount: 46600,
        offset: 2,
        coverGradient: "linear-gradient(135deg, #e6d7b8 0%, #cebfa7 100%)",
      },
      {
        id: "chaos",
        title: "Chaos",
        author: "James Gleick",
        readMoreUrl:
          "https://en.wikipedia.org/wiki/Chaos:_Making_a_New_Science",
        wordCount: 120000,
        offset: -2,
        coverGradient: "linear-gradient(135deg, #bed9e4 0%, #b7bdd9 100%)",
      },
      {
        id: "crime-and-punishment",
        title: "Crime and Punishment",
        author: "Fyodor Dostoevsky",
        readMoreUrl: "https://en.wikipedia.org/wiki/Crime_and_Punishment",
        wordCount: 206544,
        offset: 1,
        coverGradient: "linear-gradient(135deg, #d7c0c3 0%, #b2bbc7 100%)",
      },
      {
        id: "philosophy-of-software-design",
        title: "A Philosophy of Software Design",
        author: "John Ousterhout",
        readMoreUrl: "https://web.stanford.edu/~ouster/cgi-bin/book.php",
        wordCount: 50000,
        offset: -1,
        coverGradient: "linear-gradient(135deg, #d9decd 0%, #adc9c1 100%)",
      },
      {
        id: "brave-new-world",
        title: "Brave New World",
        author: "Aldous Huxley",
        readMoreUrl: "https://en.wikipedia.org/wiki/Brave_New_World",
        wordCount: 63766,
        offset: 3,
        coverGradient: "linear-gradient(135deg, #d2d7e5 0%, #b8cad2 100%)",
      },
      {
        id: "german-ideology",
        title: "The German Ideology",
        author: "Karl Marx and Friedrich Engels",
        readMoreUrl: "https://en.wikipedia.org/wiki/The_German_Ideology",
        wordCount: 120000,
        offset: -3,
        coverGradient: "linear-gradient(135deg, #e0c5bf 0%, #c8b6aa 100%)",
      },
    ],
  },
  {
    id: "stack-seed-3",
    label: "Stack seed 3",
    books: [
      {
        id: "notes-from-underground",
        title: "Notes from Underground",
        author: "Fyodor Dostoevsky",
        readMoreUrl: "https://en.wikipedia.org/wiki/Notes_from_Underground",
        wordCount: 53120,
        offset: -3,
        coverGradient: "linear-gradient(135deg, #cfc8d8 0%, #c0bfd4 100%)",
      },
      {
        id: "poor-charlies-almanack",
        title: "Poor Charlie's Almanack",
        author: "Charlie Munger",
        readMoreUrl: "https://press.stripe.com/poor-charlies-almanack",
        wordCount: 130000,
        offset: 1,
        coverGradient: "linear-gradient(135deg, #e3d4b8 0%, #c8c2a8 100%)",
      },
      {
        id: "sapiens",
        title: "Sapiens",
        author: "Yuval Noah Harari",
        readMoreUrl:
          "https://en.wikipedia.org/wiki/Sapiens:_A_Brief_History_of_Humankind",
        wordCount: 156000,
        offset: -1,
        coverGradient: "linear-gradient(135deg, #c5d8e2 0%, #b5c1d0 100%)",
      },
      {
        id: "psycho",
        title: "Psycho",
        author: "Robert Bloch",
        readMoreUrl: "https://en.wikipedia.org/wiki/Psycho_(novel)",
        wordCount: 70000,
        offset: 2,
        coverGradient: "linear-gradient(135deg, #d9c8d2 0%, #b6b7c7 100%)",
      },
      {
        id: "metamorphosis",
        title: "The Metamorphosis",
        author: "Franz Kafka",
        readMoreUrl: "https://en.wikipedia.org/wiki/The_Metamorphosis",
        wordCount: 21180,
        offset: -2,
        coverGradient: "linear-gradient(135deg, #d8d0c4 0%, #bbb9ad 100%)",
      },
      {
        id: "bitcoin-whitepaper",
        title: "Bitcoin Whitepaper",
        author: "Satoshi Nakamoto",
        readMoreUrl: "https://en.wikipedia.org/wiki/Bitcoin",
        wordCount: 3500,
        offset: 3,
        coverGradient: "linear-gradient(135deg, #ead7b5 0%, #d5bea0 100%)",
      },
    ],
  },
  {
    id: "stack-seed-4",
    label: "Stack seed 4",
    books: [
      {
        id: "feline-philosophy",
        title: "Feline Philosophy",
        author: "John Gray",
        readMoreUrl: "https://en.wikipedia.org/wiki/Feline_Philosophy",
        wordCount: 50000,
        offset: 2,
        coverGradient: "linear-gradient(135deg, #d7dbbf 0%, #c0c7ad 100%)",
      },
      {
        id: "designing-data-intensive-applications",
        title: "Designing Data-Intensive Applications",
        author: "Martin Kleppmann",
        readMoreUrl: "https://dataintensive.net/",
        wordCount: 170000,
        offset: -2,
        coverGradient: "linear-gradient(135deg, #bfd8dc 0%, #aebfd2 100%)",
      },
      {
        id: "myth-of-sisyphus",
        title: "The Myth of Sisyphus",
        author: "Albert Camus",
        readMoreUrl: "https://en.wikipedia.org/wiki/The_Myth_of_Sisyphus",
        wordCount: 54000,
        offset: 1,
        coverGradient: "linear-gradient(135deg, #d5c9dc 0%, #d0c1a8 100%)",
      },
      {
        id: "sorcerers-stone",
        title: "Harry Potter and the Sorcerer's Stone",
        author: "J.K. Rowling",
        readMoreUrl:
          "https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone",
        wordCount: 76944,
        offset: -1,
        coverGradient: "linear-gradient(135deg, #e2c7b7 0%, #c5b9d6 100%)",
      },
      {
        id: "divine-comedy",
        title: "The Divine Comedy",
        author: "Dante Alighieri",
        readMoreUrl: "https://en.wikipedia.org/wiki/Divine_Comedy",
        wordCount: 101000,
        offset: 3,
        coverGradient: "linear-gradient(135deg, #dfc8bd 0%, #c8b5ac 100%)",
      },
      {
        id: "on-liberty",
        title: "On Liberty",
        author: "John Stuart Mill",
        readMoreUrl: "https://en.wikipedia.org/wiki/On_Liberty",
        wordCount: 47740,
        offset: -3,
        coverGradient: "linear-gradient(135deg, #d5d7c3 0%, #b7c5c8 100%)",
      },
    ],
  },
  {
    id: "stack-seed-5",
    label: "Stack seed 5",
    books: [
      {
        id: "trial-and-death-of-socrates",
        title: "The Trial and Death of Socrates",
        author: "Plato",
        readMoreUrl:
          "https://en.wikipedia.org/wiki/The_Trial_and_Death_of_Socrates",
        wordCount: 45000,
        offset: -2,
        coverGradient: "linear-gradient(135deg, #dfd6bb 0%, #c9c1aa 100%)",
      },
      {
        id: "dracula",
        title: "Dracula",
        author: "Bram Stoker",
        readMoreUrl: "https://en.wikipedia.org/wiki/Dracula",
        wordCount: 164351,
        offset: 1,
        coverGradient: "linear-gradient(135deg, #c6c8d4 0%, #d1aeb4 100%)",
      },
      {
        id: "gay-science",
        title: "The Gay Science",
        author: "Friedrich Nietzsche",
        readMoreUrl: "https://en.wikipedia.org/wiki/The_Gay_Science",
        wordCount: 93000,
        offset: -1,
        coverGradient: "linear-gradient(135deg, #d7c4dd 0%, #b9c5d8 100%)",
      },
      {
        id: "the-lightning-thief",
        title: "The Lightning Thief",
        author: "Rick Riordan",
        readMoreUrl: "https://en.wikipedia.org/wiki/The_Lightning_Thief",
        wordCount: 87223,
        offset: 3,
        coverGradient: "linear-gradient(135deg, #c4d9e6 0%, #b9c4d9 100%)",
      },
      {
        id: "inner-excellence",
        title: "Inner Excellence",
        author: "Jim Murphy",
        readMoreUrl: "https://innerexcellence.com/",
        wordCount: 75000,
        offset: -3,
        coverGradient: "linear-gradient(135deg, #d6dec6 0%, #b7cbbd 100%)",
      },
      {
        id: "engines-that-move-markets",
        title: "Engines That Move Markets",
        author: "Alasdair Nairn",
        readMoreUrl:
          "https://harriman-house.com/authors/alasdair-nairn/engines-that-move-markets/9780857195999",
        wordCount: 105000,
        offset: 2,
        coverGradient: "linear-gradient(135deg, #d6d2c0 0%, #b8c9d4 100%)",
      },
    ],
  },
];
