import type { Student } from "@/types/resume";

export const STUDENTS: Student[] = [
  {
    name: "Alessandra Alinea",
    alt: "AA",
    start: "2018-09-01",
    end: "2023-08-01",
    achievements: [
      "Creative Challenge Champion, Amerikick Internationals 2022",
      "Overall Weapons Winner, Amerikick Internationals 2023",
      "NASKA World Champion",
    ],
    divisions: ["Traditional Weapons", "Traditional Forms", "CMX Weapons"],
    image: "images/aleegator.png",
  },
  {
    name: "Matthew Shamet",
    alt: "MS",
    start: "2019-02-01",
    end: "2022-03-01",
    achievements: [
      "Overall Weapons Winnder, Amerikick Internationals 2021",
      "NASKA Top 10 Competitor",
      "NASKA World Champion",
    ],
    divisions: ["Traditional Weapons", "Traditional Forms"],
    image: "images/shamet.png",
  },
  {
    name: "John Lorenz",
    alt: "JL",
    start: "2021-01-01",
    end: null,
    achievements: [
      "Team Captain, Amerikick National Team",
      "Overall Weapons Winnder, Ocean State Grand Nationals 2024",
      "Overall Weapons Winnder, Pan American Internationals 2024",
      "NASKA World Champion",
    ],
    divisions: ["CMX Weapons", "CMX Forms"],
    image: "images/JOHN.png",
  },
  {
    name: "Samantha Mitling",
    alt: "SM",
    start: "2022-06-01",
    end: null,
    achievements: [
      "Overall Weapons Grand Champion, Quebec Open 2023",
      "Overall Weapons Grand Champion, Pan American Internationals 2024",
      "NASKA World Champion",
    ],
    divisions: ["Traditional Weapons", "CMX Weapons"],
    image: "images/sam.png",
  },
  {
    name: "Derrick Barnes",
    alt: "DB",
    start: "2022-11-01",
    end: "2023-08-01",
    achievements: [
      "Creative Weapons Winner, Quebec Open 2023",
      "Mens Extreme Forms Winner, Amerikick Internationals 2023",
      "NASKA Top 10 Competitor",
    ],
    divisions: ["Traditional Weapons", "CMX Weapons"],
    image: "images/barnes.png",
  },
  {
    name: "Niko Torofias",
    alt: "NT",
    start: "2023-01-01",
    end: "2024-01-01",
    achievements: ["NASKA First Place Winner", "NASKA Top 10 Competitor"],
    divisions: ["Traditional Weapons", "CMX Weapons", "Point Fighting"],
    image: "images/niko.png",
  },
  {
    name: "Cate Esmond",
    alt: "CE",
    start: "2023-02-01",
    end: null,
    achievements: [
      "Multiple NASKA Regional Division Wins",
      "Multiple NASKA Regional Grand Championships ",
      "NASKA Top 10 Competitor",
    ],
    divisions: ["Traditional Weapons"],
    image: "images/cate.png",
  },
  {
    name: "Harold Lerner",
    alt: "HL",
    start: "2023-05-01",
    end: null,
    achievements: [
      "Overall Weapons Winnder, Ocean State Grand Nationals 2024",
      "Overall Weapons Winnder, Quebec Open 2024",
      "NASKA World Champion",
    ],
    divisions: ["Traditional Weapons", "CMX Weapons"],
    image: "images/h.png",
  },
  {
    name: "Erica Goldt",
    alt: "HL",
    start: "2023-08-01",
    end: "2024-06-01",
    achievements: ["ATA World Champion", "NASKA Top 10 Competitor"],
    divisions: ["Traditional Weapons", "Traditional Forms", "CMX Weapons"],
    image: "images/erica.png",
  },
  {
    name: "Wyatt Mak",
    alt: "WM",
    start: "2023-10-01",
    end: null,
    achievements: [
      "2 Time Grand Champion, NY Tournament",
      "NASKA Top 10 Competitor",
    ],
    divisions: ["CMX Weapons", "Point Fighting"],
    image: "images/wyatt.png",
  },
  {
    name: "Lola Granger",
    alt: "LG",
    start: "2024-01-01",
    end: null,
    achievements: [
      "Open Forms Grand Champion, NY Tournaments 2024",
      "NASKA Top 10 Competitor",
    ],
    divisions: ["CMX Weapons"],
    image: "images/lola.png",
  },
];
